services:
  redis:
    image: bitnamilegacy/redis:7.4.2
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - 7000:6379
  redis-node-0: &redis-node
    image: docker.io/bitnamilegacy/redis-cluster:7.4.2
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_NODES: "redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis-node-1:
    <<: *redis-node

  redis-node-2:
    <<: *redis-node

  redis-node-3:
    <<: *redis-node

  redis-node-4:
    <<: *redis-node

  redis-node-5:
    image: docker.io/bitnamilegacy/redis-cluster:7.4.2
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_NODES: "redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
      REDIS_CLUSTER_REPLICAS: 1
      REDIS_CLUSTER_CREATOR: "yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - 7001:6379

  redis-master:
    image: bitnamilegacy/redis:7.4.2
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis-sentinel:
    image: bitnamilegacy/redis-sentinel:7.4.2
    depends_on:
      - redis-master
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_MASTER_HOST: "redis-master"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - 7002:26379
